#!/bin/bash
set -x

echo Starting to unbind the GPU... >> /home/shigoyal/Documents/gpu_passthrough/libvert_hooks/log

# Stop display manager
systemctl stop display-manager.service
# Gnome is kinda buggy and stopping the display manager doesn't always stop
# the real Gnome display manager, so manually do it
killall gdm-x-session

# Unbind VTconsoles
echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind

# Unbind EFI-Framebuffer
echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

# Avoid a Race condition by waiting 2 seconds.
sleep 2

# Unbind the GPU from display driver
virsh nodedev-detach pci_0000_0a_00_0
virsh nodedev-detach pci_0000_0a_00_1

# Unbind the Audio controller
virsh nodedev-detach pci_0000_0c_00_4

# Load VFIO Kernel Module
modprobe vfio-pci

# Stop audio service
pulseaudio --kill

# Set up port forwarding for RDC etc
iptables -t nat -I PREROUTING -p tcp -d 192.168.0.100 --dport 3389 -j DNAT \
    --to 192.168.122.100:3389
iptables -t filter -I FORWARD -p tcp -d 192.168.122.100 --dport 3389 -j ACCEPT

echo Finished unbinding the GPU... >> /home/shigoyal/Documents/gpu_passthrough/libvert_hooks/log

